### ISSUE TITLE
IOC uses the default prefix

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lcls-plc-kfe-gatt#1]
See https://github.com/pcdshub/lcls-plc-kfe-gatt/blob/1b17239409d88bacc5dc4105c5c289f1130052c6/iocBoot/ioc-plc-kfe-gatt/Makefile#L12

Should probably be `PLC:KFE:GATT:`?

Noticed while discussing https://github.com/pcdshub/pmps-ui/issues/26

**Comment by klauer** [comment]
This was fixed in https://github.com/pcdshub/lcls-plc-kfe-gatt/pull/3/files
