### ISSUE TITLE
Inverted fork

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lcls-plc-kfe-gatt#2]
This pcdshub repo is forked from ghalym/lcls-plc-kfe-gatt, but it should have been the original and ghalym/lcls-plc-kfe-gatt should have been the fork. I'm not sure what the implications are with that in terms of using the github interface (it should have no direct effect on the project itself)

**Comment by ZLLentz** [comment]
Apparently forks are not indexed for code searching in github

**Comment by klauer** [comment]
I just opened a ticket here to "extract" this fork from @slacAWallace:
https://support.github.com/contact?tags=rr-forks&subject=Detach%20Fork&flow=detach_fork
